channels:
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip=21.0
  - faiss-gpu
  - pytorch=1.13.1
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - cudatoolkit=11.3
  - gcc=9.4.0
  - gxx=9.4.0
  - pip:
      - bitarray
      - datasets
      - gitpython
      - jupyter
      - jupyterlab
      - ninja
      - scipy
      - tqdm
      - transformers
      - ujson
      - flask
      - python-dotenv

